import { Audio } from 'expo-av';
import * as Speech from 'expo-speech';

const AUDIO_MAP: Record<string, any> = {
  '爱': require('../../assets/audio/ai.mp3'),
  '吧': require('../../assets/audio/ba.mp3'),
  '爸爸': require('../../assets/audio/baba.mp3'),
  '杯': require('../../assets/audio/bei.mp3'),
  '本': require('../../assets/audio/ben.mp3'),
  '不': require('../../assets/audio/bu.mp3'),
  '菜': require('../../assets/audio/cai.mp3'),
  '车': require('../../assets/audio/che.mp3'),
  '吃': require('../../assets/audio/chi.mp3'),
  '的': require('../../assets/audio/de.mp3'),
  '点': require('../../assets/audio/dian.mp3'),
  '电视': require('../../assets/audio/dianshi.mp3'),
  '电影': require('../../assets/audio/dianying.mp3'),
  '东西': require('../../assets/audio/dongxi.mp3'),
  '都': require('../../assets/audio/dou.mp3'),
  '对': require('../../assets/audio/dui.mp3'),
  '儿': require('../../assets/audio/er.mp3'),
  '分': require('../../assets/audio/fen.mp3'),
  '高': require('../../assets/audio/gao.mp3'),
  '个': require('../../assets/audio/ge.mp3'),
  '工作': require('../../assets/audio/gongzuo.mp3'),
  '狗': require('../../assets/audio/gou.mp3'),
  '好': require('../../assets/audio/hao.mp3'),
  '喝': require('../../assets/audio/he.mp3'),
  '和': require('../../assets/audio/he2.mp3'),
  '很': require('../../assets/audio/hen.mp3'),
  '后': require('../../assets/audio/hou.mp3'),
  '几': require('../../assets/audio/ji.mp3'),
  '叫': require('../../assets/audio/jiao.mp3'),
  '今': require('../../assets/audio/jin.mp3'),
  '了': require('../../assets/audio/le.mp3'),
  '里': require('../../assets/audio/li.mp3'),
  '吗': require('../../assets/audio/ma.mp3'),
  '妈妈': require('../../assets/audio/mama.mp3'),
  '猫': require('../../assets/audio/mao.mp3'),
  '没': require('../../assets/audio/mei.mp3'),
  '们': require('../../assets/audio/men.mp3'),
  '米': require('../../assets/audio/mi.mp3'),
  '名字': require('../../assets/audio/mingzi.mp3'),
  // Lesson vocab words (generated by edge-tts)
  '你好': require('../../assets/audio/你好.mp3'),
  '您好': require('../../assets/audio/您好.mp3'),
  '你们好': require('../../assets/audio/你们好.mp3'),
  '对不起': require('../../assets/audio/对不起.mp3'),
  '没关系': require('../../assets/audio/没关系.mp3'),
  '谢谢': require('../../assets/audio/谢谢.mp3'),
  '再见': require('../../assets/audio/再见.mp3'),
  '老师': require('../../assets/audio/老师.mp3'),
  '同学': require('../../assets/audio/同学.mp3'),
  '朋友': require('../../assets/audio/朋友.mp3'),
  '我': require('../../assets/audio/我.mp3'),
  '他': require('../../assets/audio/他.mp3'),
  '她': require('../../assets/audio/她.mp3'),
  '我们': require('../../assets/audio/我们.mp3'),
  '他们': require('../../assets/audio/他们.mp3'),
  '是': require('../../assets/audio/是.mp3'),
  '不是': require('../../assets/audio/不是.mp3'),
  '有': require('../../assets/audio/有.mp3'),
  '没有': require('../../assets/audio/没有.mp3'),
  '在': require('../../assets/audio/在.mp3'),
  '这': require('../../assets/audio/这.mp3'),
  '那': require('../../assets/audio/那.mp3'),
  '哪': require('../../assets/audio/哪.mp3'),
  '什么': require('../../assets/audio/什么.mp3'),
  '谁': require('../../assets/audio/谁.mp3'),
  '一': require('../../assets/audio/一.mp3'),
  '二': require('../../assets/audio/二.mp3'),
  '三': require('../../assets/audio/三.mp3'),
  '四': require('../../assets/audio/四.mp3'),
  '五': require('../../assets/audio/五.mp3'),
  '六': require('../../assets/audio/六.mp3'),
  '七': require('../../assets/audio/七.mp3'),
  '八': require('../../assets/audio/八.mp3'),
  '九': require('../../assets/audio/九.mp3'),
  '十': require('../../assets/audio/十.mp3'),
  '百': require('../../assets/audio/百.mp3'),
  '千': require('../../assets/audio/千.mp3'),
  '万': require('../../assets/audio/万.mp3'),
  '零': require('../../assets/audio/零.mp3'),
  '今天': require('../../assets/audio/今天.mp3'),
  '明天': require('../../assets/audio/明天.mp3'),
  '昨天': require('../../assets/audio/昨天.mp3'),
  '现在': require('../../assets/audio/现在.mp3'),
  '以前': require('../../assets/audio/以前.mp3'),
  '年': require('../../assets/audio/年.mp3'),
  '月': require('../../assets/audio/月.mp3'),
  '日': require('../../assets/audio/日.mp3'),
  '号': require('../../assets/audio/号.mp3'),
  '星期': require('../../assets/audio/星期.mp3'),
  '上午': require('../../assets/audio/上午.mp3'),
  '下午': require('../../assets/audio/下午.mp3'),
  '晚上': require('../../assets/audio/晚上.mp3'),
  '早上': require('../../assets/audio/早上.mp3'),
  '中国': require('../../assets/audio/中国.mp3'),
  '北京': require('../../assets/audio/北京.mp3'),
  '上海': require('../../assets/audio/上海.mp3'),
  '学校': require('../../assets/audio/学校.mp3'),
  '家': require('../../assets/audio/家.mp3'),
  '中文': require('../../assets/audio/中文.mp3'),
  '汉语': require('../../assets/audio/汉语.mp3'),
  '英语': require('../../assets/audio/英语.mp3'),
  '日语': require('../../assets/audio/日语.mp3'),
  '学习': require('../../assets/audio/学习.mp3'),
  '吃饭': require('../../assets/audio/吃饭.mp3'),
  '喝水': require('../../assets/audio/喝水.mp3'),
  '睡觉': require('../../assets/audio/睡觉.mp3'),
  '去': require('../../assets/audio/去.mp3'),
  '来': require('../../assets/audio/来.mp3'),
  '回': require('../../assets/audio/回.mp3'),
  '走': require('../../assets/audio/走.mp3'),
  '坐': require('../../assets/audio/坐.mp3'),
  '看': require('../../assets/audio/看.mp3'),
  '听': require('../../assets/audio/听.mp3'),
  '说': require('../../assets/audio/说.mp3'),
  '写': require('../../assets/audio/写.mp3'),
  '读': require('../../assets/audio/读.mp3'),
  '大': require('../../assets/audio/大.mp3'),
  '小': require('../../assets/audio/小.mp3'),
  '多': require('../../assets/audio/多.mp3'),
  '少': require('../../assets/audio/少.mp3'),
  '贵': require('../../assets/audio/贵.mp3'),
  '好吃': require('../../assets/audio/好吃.mp3'),
  '好喝': require('../../assets/audio/好喝.mp3'),
  '漂亮': require('../../assets/audio/漂亮.mp3'),
  '高兴': require('../../assets/audio/高兴.mp3'),
  '累': require('../../assets/audio/累.mp3'),
  '热': require('../../assets/audio/热.mp3'),
  '冷': require('../../assets/audio/冷.mp3'),
  '快': require('../../assets/audio/快.mp3'),
  '慢': require('../../assets/audio/慢.mp3'),
  '人': require('../../assets/audio/人.mp3'),
  '书': require('../../assets/audio/书.mp3'),
  '水': require('../../assets/audio/水.mp3'),
  '饭': require('../../assets/audio/饭.mp3'),
  '茶': require('../../assets/audio/茶.mp3'),
  '咖啡': require('../../assets/audio/咖啡.mp3'),
  '苹果': require('../../assets/audio/苹果.mp3'),
  '西瓜': require('../../assets/audio/西瓜.mp3'),
  '米饭': require('../../assets/audio/米饭.mp3'),
  '面条': require('../../assets/audio/面条.mp3'),
  '医生': require('../../assets/audio/医生.mp3'),
  '学生': require('../../assets/audio/学生.mp3'),
  '司机': require('../../assets/audio/司机.mp3'),
  '厨师': require('../../assets/audio/厨师.mp3'),
  '哥哥': require('../../assets/audio/哥哥.mp3'),
  '姐姐': require('../../assets/audio/姐姐.mp3'),
  '弟弟': require('../../assets/audio/弟弟.mp3'),
  '妹妹': require('../../assets/audio/妹妹.mp3'),
  '儿子': require('../../assets/audio/儿子.mp3'),
  '女儿': require('../../assets/audio/女儿.mp3'),
  '丈夫': require('../../assets/audio/丈夫.mp3'),
  '妻子': require('../../assets/audio/妻子.mp3'),
  '飞机': require('../../assets/audio/飞机.mp3'),
  '火车': require('../../assets/audio/火车.mp3'),
  '出租车': require('../../assets/audio/出租车.mp3'),
  '公共汽车': require('../../assets/audio/公共汽车.mp3'),
  '医院': require('../../assets/audio/医院.mp3'),
  '商店': require('../../assets/audio/商店.mp3'),
  '饭馆': require('../../assets/audio/饭馆.mp3'),
  '银行': require('../../assets/audio/银行.mp3'),
  '电话': require('../../assets/audio/电话.mp3'),
  '手机': require('../../assets/audio/手机.mp3'),
  '电脑': require('../../assets/audio/电脑.mp3'),
  '钱': require('../../assets/audio/钱.mp3'),
  '块': require('../../assets/audio/块.mp3'),
  '毛': require('../../assets/audio/毛.mp3'),
  '岁': require('../../assets/audio/岁.mp3'),
  '国籍': require('../../assets/audio/国籍.mp3'),
};

let currentSound: Audio.Sound | null = null;

export function getAudioForWord(text: string) {
  return AUDIO_MAP[text] ?? null;
}

export async function stopCurrentSound() {
  if (currentSound) {
    try {
      await currentSound.stopAsync();
      await currentSound.unloadAsync();
    } catch (e) {
      console.warn('Error stopping sound:', e);
    } finally {
      currentSound = null;
    }
  }
}

export async function playAudioFile(
  audioFile: any,
  onPlaybackStatusUpdate?: (status: any) => void,
  waitForCompletion: boolean = true
): Promise<Audio.Sound> {
  await stopCurrentSound();
  const { sound } = await Audio.Sound.createAsync(audioFile, { shouldPlay: true });
  currentSound = sound;
  if (!waitForCompletion) {
    sound.setOnPlaybackStatusUpdate((status) => {
      if (onPlaybackStatusUpdate) {
        onPlaybackStatusUpdate(status);
      }
      if (status.isLoaded && status.didJustFinish && currentSound === sound) {
        currentSound = null;
      }
    });
    return sound;
  }

  await new Promise<void>((resolve) => {
    sound.setOnPlaybackStatusUpdate((status) => {
      if (onPlaybackStatusUpdate) {
        onPlaybackStatusUpdate(status);
      }
      if (status.isLoaded && status.didJustFinish) {
        sound.unloadAsync();
        if (currentSound === sound) {
          currentSound = null;
        }
        resolve();
      }
    });
  });
  return sound;
}

async function speakWithTtsFallback(text: string) {
  const langOptions = [
    { language: 'zh-CN', rate: 0.85 },
    { language: 'zh', rate: 0.85 },
    { language: 'cmn-CN', rate: 0.85 },
  ];
  let spoken = false;
  for (const opts of langOptions) {
    try {
      Speech.speak(text, opts);
      spoken = true;
      break;
    } catch {}
  }
  if (!spoken) Speech.speak(text);
}

function getCharacterAudioSequence(text: string) {
  const chars = [...text.trim()];
  if (chars.length < 2) return null;
  const sequence = chars.map((char) => AUDIO_MAP[char]).filter(Boolean);
  return sequence.length === chars.length ? sequence : null;
}

export async function speakChinese(text: string) {
  try {
    await stopCurrentSound();

    const audioFile = AUDIO_MAP[text];

    if (audioFile) {
      // Play high-quality pre-recorded MP3
      await Audio.setAudioModeAsync({
        playsInSilentModeIOS: true,
        staysActiveInBackground: false,
        shouldDuckAndroid: false,
        playThroughEarpieceAndroid: false,
      });
      await playAudioFile(audioFile);
    } else {
      const charSequence = getCharacterAudioSequence(text);
      if (charSequence) {
        await Audio.setAudioModeAsync({
          playsInSilentModeIOS: true,
          staysActiveInBackground: false,
          shouldDuckAndroid: false,
          playThroughEarpieceAndroid: false,
        });
        for (const file of charSequence) {
          await playAudioFile(file);
        }
      } else {
        // Fallback: use device TTS for words without a recorded file
        await speakWithTtsFallback(text);
      }
    }
  } catch (e) {
    console.warn('Audio playback error:', e);
    // Last resort fallback
    try {
      await speakWithTtsFallback(text);
    } catch {}
  }
}
